apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeprice-deployment
  labels:
    app: homeprice
spec:
  replicas: 2  # You can adjust based on your load
  selector:
    matchLabels:
      app: homeprice
  template:
    metadata:
      labels:
        app: homeprice
    spec:
      containers:
      - name: homeprice-container
        image: mjid6/home_price:v1
        ports:
        - containerPort: 80  # Frontend (nginx)
        - containerPort: 5000  # Backend (Flask or FastAPI)
