apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-price-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-price-front
  template:
    metadata:
      labels:
        app: home-price-front
    spec:
      containers:
      - name: home-price-front
        image: mjid6/home-price-front:v1
        ports:
        - containerPort: 80
