apiVersion: v1
kind: Service
metadata:
  name: home-price-front-service
spec:
  type: NodePort
  selector:
    app: home-price-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
