apiVersion: v1
kind: Service
metadata:
  name: homeprice-service
spec:
  selector:
    app: homeprice
  ports:
  - name: http  # Added name for frontend port
    protocol: TCP
    port: 80  # Frontend port
    targetPort: 80  # Exposing the frontend port
    nodePort: 30080  # External port for frontend
  - name: api  # Added name for backend port
    protocol: TCP
    port: 5000  # Backend port
    targetPort: 5000  # Exposing the backend port
    nodePort: 30000  # External port for backend
  type: NodePort
