apiVersion: v1
kind: Service
metadata:
  name: homeprice-service
spec:
  selector:
    app: homeprice
  ports:
  - name: api  
    protocol: TCP
    port: 9090 
    targetPort: 9090  
    nodePort: 30000  
  type: NodePort
