apiVersion: v1
kind: Service
metadata:
  name: homeprice-frontend-service
spec:
  selector:
    app: homeprice-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 50000  
  type: NodePort
